# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name:		icon-slicer
Version:	0.3
Release:	5
Summary:	Utility for icon theme generation
License:	MIT
Group:		Development/Other
Url:		http://www.freedesktop.org/software/icon-slicer/

Source:		http://www.freedesktop.org/software/icon-slicer/releases/icon-slicer-0.3.tar.gz

Patch:		icon-slicer-0.3-sugar-297.patch

BuildRequires:	pkgconfig(gtk+-2.0)
BuildRequires:	pkgconfig(popt)

%description
Utility for generating icon themes and libXcursor cursor themes.

%prep
%setup -q -n icon-slicer-0.3
%patch -p1

%build
%define __libtoolize true
%configure
make

%install
%makeinstall_std

%files 
%{_bindir}/%{name}
%doc AUTHORS ChangeLog README TODO

