# NOTE: Do not edit, file was generated by jhconvert

Name: icon-slicer
Version: 0.3
Release: %mkrel 2
Summary: Utility for icon theme generation
License: MIT
Group: Development/Other
Url: http://www.freedesktop.org/software/icon-slicer/

Source: http://www.freedesktop.org/software/icon-slicer/releases/icon-slicer-0.3.tar.gz

Patch: icon-slicer-0.3-sugar-297.patch

BuildRequires: pkgconfig
BuildRequires: xcursorgen
BuildRequires: libgtk+2-devel
BuildRequires: libpopt-devel

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
Utility for generating icon themes and libXcursor cursor themes.

%prep
%setup -q
%patch -p1

%build
%configure
make

%install
rm -rf %{buildroot}
make DESTDIR=%{buildroot} install

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%doc AUTHORS ChangeLog README TODO

